Import các thư viện cần thiết như Numpy và Pandas

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

NumPy: 2.3.5
Pandas: 2.3.3

Đọc datasets

In [12]:
df = pd.read_csv("../data/diabetes.csv")
print(df.shape) # Kích thước có 768 bệnh nhân và 9 cột bệnh lý
print('==================================================')
print(df.info()) #Thông tin kiểu dữ liệu của datasets
print('==================================================')
print(df.head(10))#Hiển thị 10 dòng giá trị đầu tiên 
print('==================================================')
print(df.describe())#Xem thống kê

(768, 9)
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB
None
==================================================
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35        0  33.6                     0.627   50        1
1            1       85             66             29        0  26.6                     0.351   31        0
2            8      183             64              0        0  23.3                     0.672   32        1
3            1       89             66             23       94  28.1                     0.167   21        0
4            0      137             40             35      168  43.1                     2.288   33        1
5            5      116             74              0        0  25.6                     0.201   30        0
6            3       78             50             32       88  31.0                     0.248   26        1
7           10      115              0              0        0  35.3                     0.134   29        0
8            2      197             70             45      543  30.5                     0.158   53        1
9            8      125             96              0        0   0.0                     0.232   54        1
==================================================
       Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin         BMI  DiabetesPedigreeFunction         Age     Outcome
count   768.000000  768.000000     768.000000     768.000000  768.000000  768.000000                768.000000  768.000000  768.000000
mean      3.845052  120.894531      69.105469      20.536458   79.799479   31.992578                  0.471876   33.240885    0.348958
std       3.369578   31.972618      19.355807      15.952218  115.244002    7.884160                  0.331329   11.760232    0.476951
min       0.000000    0.000000       0.000000       0.000000    0.000000    0.000000                  0.078000   21.000000    0.000000
25%       1.000000   99.000000      62.000000       0.000000    0.000000   27.300000                  0.243750   24.000000    0.000000
50%       3.000000  117.000000      72.000000      23.000000   30.500000   32.000000                  0.372500   29.000000    0.000000
75%       6.000000  140.250000      80.000000      32.000000  127.250000   36.600000                  0.626250   41.000000    1.000000
max      17.000000  199.000000     122.000000      99.000000  846.000000   67.100000                  2.420000   81.000000    1.000000

Kiểm tra giá trị bất thường

In [13]:
cols = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']

zero_values = (df[cols] == 0).sum()

zero_table = pd.DataFrame({
    "Feature": zero_values.index,
    "Zero Values": zero_values.values,
    "Percentage %": (zero_values / len(df) * 100).round(3)
})

print("Các giá trị 0 bất thường")
display(zero_table)

df[cols] = df[cols].replace(0, np.nan)

Các giá trị 0 bất thường

                     Feature  Zero Values  Percentage %
Glucose              Glucose            5         0.651
BloodPressure  BloodPressure           35         4.557
SkinThickness  SkinThickness          227        29.557
Insulin              Insulin          374        48.698
BMI                      BMI           11         1.432

Thống kê dữ liệu

In [9]:
eda_summary = pd.DataFrame({
    "Feature": df.columns,
    "Missing Values": df.isnull().sum().values,
    "Missing %": (df.isnull().mean() * 100).round(3).values,
    "Mean": df.mean().round(3).values,
    "Std": df.std().round(3).values,
    "Min": df.min().values,
    "Max": df.max().values
})
print("Bảng thống kê dữ liệu")
display(eda_summary.sort_values('Missing %',ascending=False).reset_index(drop=True))

Bảng thống kê dữ liệu

                    Feature  Missing Values  Missing %     Mean      Std     Min     Max
0               Pregnancies               0        0.0    3.845    3.370   0.000   17.00
1                   Glucose               0        0.0  120.895   31.973   0.000  199.00
2             BloodPressure               0        0.0   69.105   19.356   0.000  122.00
3             SkinThickness               0        0.0   20.536   15.952   0.000   99.00
4                   Insulin               0        0.0   79.799  115.244   0.000  846.00
5                       BMI               0        0.0   31.993    7.884   0.000   67.10
6  DiabetesPedigreeFunction               0        0.0    0.472    0.331   0.078    2.42
7                       Age               0        0.0   33.241   11.760  21.000   81.00
8                   Outcome               0        0.0    0.349    0.477   0.000    1.00

Xử lý misssing

In [14]:
imputer = SimpleImputer(strategy="median")
df[cols] = imputer.fit_transform(df[cols])

Scaling

In [15]:
scaler = StandardScaler()

X = df.drop("Outcome", axis=1)
y = df["Outcome"]

X_scaled = scaler.fit_transform(X)

df_clean = pd.DataFrame(X_scaled, columns=X.columns)
df_clean["Outcome"] = y.values

df_clean.head()

   Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  DiabetesPedigreeFunction       Age  Outcome
0     0.639947  0.866045      -0.031990       0.670643 -0.181541  0.166619                  0.468492  1.425995        1
1    -0.844885 -1.205066      -0.528319      -0.012301 -0.181541 -0.852200                 -0.365061 -0.190672        0
2     1.233880  2.016662      -0.693761      -0.012301 -0.181541 -1.332500                  0.604397 -0.105584        1
3    -0.844885 -1.073567      -0.528319      -0.695245 -0.540642 -0.633881                 -0.920763 -1.041549        0
4    -1.141852  0.504422      -2.679076       0.670643  0.316566  1.549303                  5.484909 -0.020496        1